services:
  db:
    image: mysql:8.0.40
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app:cached
      - bundle-volume:/usr/local/bundle
    ports:
      - 25021:3000
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  bundle-volume:
  mysql-data:
